config/routes.rb
Rails.application.routes.draw do
  resources :exercise_logs
  resources :exercises do 
    resources :exercise_logs, only:[:index, :new]
  end 
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show]
  root 'exercises#index'

  # resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
    has_many :exercise_logs
    has_many :users, -> { distinct }, through: :exercise_logs
    validates :name, presence: true, uniqueness: true
    

    def self.popular
        order(exercise_log_count: :desc)
    end 
    
    def self.alphabetical 
        order(:name, exercise: :asc)
    end 

end

app/models/exercise_log.rb
class ExerciseLog < ApplicationRecord
  belongs_to :user
  belongs_to :exercise, counter_cache: :exercise_log_count  
  validate :reps_weight_duration_and_notes


  def reps_weight_duration_and_notes
    unless (reps.present? && weight.present?) || duration.present? || notes.present? 
      self.errors.add(:not_implemented, "workout must contain either reps and weight, duration, or notes")
    end
  end 

  def self.highest_duration
    order(duration: :desc)
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable, :validatable, :recoverable, :rememberable, :omniauthable, omniauth_providers: [:google_oauth2]
    has_many :exercise_logs 
    has_many :exercises, -> { distinct }, through: :exercise_logs 
    validates :email, presence: true, uniqueness: true
    validates :user_name, uniqueness: true, if: -> {user_name.present?}
    
    def self.from_google(uid:, email:, full_name:, avatar_url:)
      if user = User.find_by(email: email)
        user.update(uid: uid, full_name: full_name, avatar_url: avatar_url) unless user.uid.present?
        user
      else
        User.create(
          email: email,
          uid: uid,
          full_name: full_name,
          avatar_url: avatar_url,
          password: SecureRandom.hex
        )
      end
    end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    def not_found
        flash[:error] = "Not found"
        redirect_to root_path
    end 

    protected 

    def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :email])
    end 
end

app/controllers/exercise_logs_controller.rb
class ExerciseLogsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_exercise_log, only: [:show, :edit, :update, :destroy]
    
    def index 
        @exercise = Exercise.find_by_id(params[:exercise_id])  
        if @exercise
            @exercise_logs = @exercise.exercise_logs
        else 
            @exercise_logs = current_user.exercise_logs
        end
        filter_options
    end 

    def show 

    end 

    def new 
        @exercise = Exercise.find_by_id(params[:exercise_id])
        if @exercise
            @exercise_log = @exercise.exercise_logs.build
        else 
            @exercise_log = ExerciseLog.new   
        end 
         
    end 
    
    def create 
        @exercise_log = current_user.exercise_logs.build(exercise_log_params)
        if @exercise_log.save 
            redirect_to exercise_log_path(@exercise_log)
        else 
            render :new 
        end  
    end 

    def edit 

    end 

    def update
        if @exercise_log.update(exercise_log_params)
            redirect_to exercise_log_path(@exercise_log)
        else 
            render :edit
        end 
    end 

    def destroy 
        @exercise_log.destroy
        redirect_to exercise_logs_path
    end 

    private

    def set_exercise_log
        @exercise_log = current_user.exercise_logs.find(params[:id])
    end 

    def filter_options
        if params[:sort] == "highest_duration"
            @exercise_logs = @exercise_logs.highest_duration
        end 
    end 

    def exercise_log_params
        params.require(:exercise_log).permit(:exercise_id, :user_id, :reps, :weight, :duration, :notes)
    end 

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_exercise, only: [:show, :edit, :update, :destroy]
    def index 
        @exercises = Exercise.all
        filter_options
    end 

    def show 
        
    end 
    
    def new 
        @exercise = Exercise.new
    end 

    def create
        @exercise = Exercise.new(exercise_params)
        if @exercise.save
            redirect_to exercise_path(@exercise)
        else 
            render :new 
        end 
    end
    

    private 

    def set_exercise
        @exercise = Exercise.find(params[:id])
    end 

    def filter_options
        if params[:sort_alphabetically] == "alphabetical"
            @exercises = @exercises.alphabetical
        end 

        if params[:sort] == "popular"
            @exercises = @exercises.popular
        end 
    end 


    def exercise_params 
        params.require(:exercise).permit(:name, :exercise_log_count)
    end 


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def google_oauth2
    user = User.from_google(from_google_params)
    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end 
  end
 
    
  protected
    
  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end
    
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
    
  private
    
  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end
    
  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  def show 
  
  end 

  private 

  def user_params 
    params.require(:user).permit(:user_name, :email)
  end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_helper.rb
module ErrorHelper
    def show_errors_for(object)
        render partial: 'shared/errors', locals: { object: object }
    end
end 

app/helpers/exercise_logs_helper.rb
module ExerciseLogsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exercise_logs/_form.html.erb
<%= show_errors_for(@exercise_log) %>
<%= form_for @exercise_log do |f| %>
    <p>
    <% if exercise_log.exercise_id %>
        <%= f.label :exercise_id, "Exercise"%>
        <%= f.hidden_field :exercise_id %>
        <%= exercise_log.exercise.name %>
        <% else %>

            <%= f.label :exercise_id, "Exercise" %>
            <%= f.collection_select :exercise_id, Exercise.all, :id, :name %>
        <% end %>
    </p>

     <p>
        <%= f.label :reps %>
        <%= f.text_field :reps %>
    </p>
     <p>
        <%= f.label :weight %>
        <%= f.text_field :weight %>

    </p>
     <p>
        <%= f.label :duration %>(minutes)
        <%= f.text_field :duration %>
    </p>
    <p>
        <%= f.label :notes %>
        <%= f.text_field :notes%>
    </p>
    <%= f.submit %>


<% end %>

app/views/exercise_logs/edit.html.erb
<h1>Edit Exercise Log</h1>
<%= render partial: 'form', locals: { exercise_log: @exercise_log} %>

app/views/exercise_logs/index.html.erb
<h1>Exercise Log</h1>
<nav>
    <button><%= link_to "Add Exercise Log", new_exercise_log_path %></button>
</nav>

<%= form_tag(exercise_logs_path, method: 'get') do %>
    <label for="sort">Sort</label>
    <select name="sort">
        <option <%= 'selected' if params[:sort] == '' %> value="">None</option>
        <option <%= 'selected' if params[:sort] == 'highest_duration' %> value="highest_duration">Highest Duration</option>
    </select>
    <%= submit_tag 'Filter Results' %>
<% end %>
<div>
<table>
    <style>
    table, th, td{border: 1px solid red; background: white;}
        th {width: 140px}
        td {width: 150px}
    </style>
    <tr>
        <th>Exercise Name</th>
        <th>Reps</th>
        <th>Weight(lbs)</th>
        <th>Duration(m)</th>
        <th>Notes</th>
    </tr>
    <% @exercise_logs.each do |exercise_log| %>
        <tr>
            <td><%= link_to exercise_log.exercise.name, edit_exercise_log_path(exercise_log) %>
            <td><%= exercise_log.reps %>
            <td><%= exercise_log.weight %>
            <td><%= exercise_log.duration %>
            <td><%= exercise_log.notes %>
        </tr> 
    <% end %>      
</table> 
</div>

app/views/exercise_logs/new.html.erb
<h1>New Exercise Log</h1>
<%= render partial: 'form', locals: { exercise_log: @exercise_log} %>

app/views/exercise_logs/show.html.erb
<h1>Exercise Log added<h1>
<button><%= link_to "Back to Exercise_log", exercise_logs_path %></button>
<p>Exercise: <%= link_to @exercise_log.exercise.name, exercise_path(@exercise_log.exercise) %></p>
<p>Reps: <%= @exercise_log.reps %></p>
<p>Weight: <%= @exercise_log.weight %>lbs</p>
<p>Duration(minutes): <%= @exercise_log.duration %></p>
<p>Notes: <%= @exercise_log.notes %></p>
<%= link_to "Edit Exercise Log", edit_exercise_log_path(@exercise_log) %>
<%= form_tag(exercise_log_path(@exercise_log), method: :delete, style: 'display: inline-block;') do %>
    <%= submit_tag "Delete Exercise Log" %>
<% end %>

app/views/exercises/index.html.erb
<h1>Exercises </h1>
<nav>
    <button><%= link_to "New Exercise", new_exercise_path %></button>
</nav>
<%= form_tag(exercises_path, method: 'get') do %>
  <label for="sort_alphabetically">Alphabetical</label>
  <select name="sort_alphabetically">
    <option <%= 'selected' if params[:sort_alphabetically] == '' %> value="">None</option>
    <option <%= 'selected' if params[:sort_alphabetically] == 'alphabetical' %> value="alphabetical">Alphabetical</option>

  </select>
  <label for="sort">Sort</label>
  <select name="sort">
    <option <%= 'selected' if params[:sort] == '' %> value="">None</option>
    <option <%= 'selected' if params[:sort] == 'popular' %> value="popular">Most Popular</option>
  </select>
  <%= submit_tag 'Filter Results' %>
<% end %>
   
<div>
<table>
    <style>
    table, th, td{border: 1px solid blue; background: yellow}
        th {width: 140px}
        td {width: 150px}
    </style>
    <tr>
        <th>Exercises</th>
        <th>Exercise Log Count</th>
        
    </tr>
    <% @exercises.each do |exercise| %>
        <tr>
            <td><%= link_to exercise.name, exercise_path(exercise) %></td>
            <td><%= exercise.exercise_log_count%>
        </tr>
    <% end %>      
</table> 
</div>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>
<%= show_errors_for(@exercise) %>

<%= form_for @exercise do |f| %>
    <p>
        <%= f.label :name, "Add name of exercise here" %><br/>
        <%= f.text_field :name %>
    </p>
    <%= f.submit %>
<% end %> 

app/views/exercises/show.html.erb
<p><%= link_to "Back to Exercises",  exercises_path %></p>
<p><%= link_to "#{@exercise.name}'s exercise logs", exercise_exercise_logs_path(@exercise) %></p>
<p><%= link_to "Add #{@exercise.name} to your log", new_exercise_exercise_log_path(@exercise) %></p>
<h2>Exercise successfully added<h2>

 <p>Exercise: <%= @exercise.name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <style>
    body {background-color: powderblue}
  </style >
  <head>
    <title>Exercise Rails App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render partial: 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end -%>
 
      <%= yield %>
    </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name %> from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
    <%= link_to "Exercises", exercises_url %>
    <%= link_to "Exercise Logs", exercise_logs_url %>
    <% if user_signed_in? %>
      <%= form_tag(destroy_user_session_path, method: :delete, style: 'display: inline-block') do %>
        <%= submit_tag "Sign Out" %>
      <% end %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>
</nav>

app/views/users/show.html.erb
<h1>Welcome</h1>

<p><%= link_to "Edit Exercise Log", new_exercise_exercise_log_path %></p> 